package com.raven.main;

import com.raven.connection.DatabaseConnection;
import com.raven.connection.koneksi;
import com.raven.event.EventMenuSelected;
import com.raven.form.FormMember;
import com.raven.form.FormMakanan;
import com.raven.form.FormLaporan;
import com.raven.form.FormHome;
import com.raven.form.FormBiaya;
import com.raven.form.FormUser;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private FormHome formHome;
    private FormMember formMember;
    private FormMakanan formMakanan;
    private FormLaporan formLaporan;
    private FormBiaya formBiaya;
    private FormUser formUser;
    
    private Color color1;
    private Color color2;
    private Connection connection;

    public Menu_Utama() {
        initComponents();
        
        setBackground(new Color(0, 0, 0, 0));
        
        formHome = new FormHome();
        formMember = new FormMember();
        formMakanan = new FormMakanan();
        formLaporan = new FormLaporan();
        formBiaya = new FormBiaya();
        formUser = new FormUser();
        
        menu.initMoving(Menu_Utama.this);
        
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(formHome);
                } /* else if (index == 1) {
                    setForm(formMember);
                } else if (index == 2) {
                    setForm(formMakanan);
                } else if (index == 3) {
                    setForm(formLaporan);
                } else if (index == 4) {
                    setForm(formUser);
                } else if (index == 5) {
                    setForm(formBiaya);
                }*/
            }
        });
        //  set when system open start with home form
        setForm(new FormHome());
        
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swing.PanelBorder();
        menu = new com.raven.component.Menu();
        mainPanel = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pool & Cafe Applications");
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(204, 255, 255));

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout(10, 10));

        jLabelClose.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelClose.setText("Close");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabelClose)
                        .addGap(29, 29, 29)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
                
            }
        }); 
    }
//   public void ModifiableBackgroundCard(){
//       JPanel jPanel = new JPanel(){
//            @Override
//            public void paintComponent(Graphics grphcs)
//            {
//                Graphics2D g2 = (Graphics2D) grphcs;
//                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//                GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
//                g2.setPaint(g);
//                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
//                g2.setColor(new Color(255, 255, 255, 50));
//                g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
//                g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
//                super.paintComponent(grphcs);
//            }
//        };
//   }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JPanel mainPanel;
    private com.raven.component.Menu menu;
    private com.raven.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
